name: Build and deploy to Kuroco front
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run generate

      - name: Zip artifact for upload
        run: cd dist && zip ../out.zip . -r

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: out.zip
          retention-days: 7

      - name: Webhook
        uses: diverta/workflow-webhook@v3
        env:
          webhook_url: "https://chino.g.kuroco.app/direct/menu/github/"
          webhook_secret: "32b04df2349a33d3b1533f0bedd5ef84"
          data: '{"single_zip":"1","domain":"chino.g.kuroco-front.app",  "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
